name: "練習棟予約システム スクレイピング"

permissions:
  contents: read

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download latest release via GH CLI
        run: |
          gh auth setup-git
          gh release download \
            --repo ${{ github.repository }} \
            --pattern scraping-obs \
            --output ./scraping-obs
          chmod +x ./scraping-obs

      - name: Run scraper
        env:
          CALENDAR_URL: ${{ secrets.CALENDAR_URL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: ./scraping-obs
